language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: LARAVEL='7.*' TESTBENCH='5.*' COMPOSER_FLAGS='--prefer-lowest' FORM_COMPONENTS_FRAMEWORK='tailwind'
    - php: 7.4
      env: LARAVEL='7.*' TESTBENCH='5.*' COMPOSER_FLAGS='--prefer-stable 'FORM_COMPONENTS_FRAMEWORK='tailwind'
    - php: 7.4
      env: LARAVEL='7.*' TESTBENCH='5.*' COMPOSER_FLAGS='--prefer-lowest' FORM_COMPONENTS_FRAMEWORK='tailwind-2'
    - php: 7.4
      env: LARAVEL='7.*' TESTBENCH='5.*' COMPOSER_FLAGS='--prefer-stable 'FORM_COMPONENTS_FRAMEWORK='tailwind-2'
    - php: 7.4
      env: LARAVEL='7.*' TESTBENCH='5.*' COMPOSER_FLAGS='--prefer-lowest 'FORM_COMPONENTS_FRAMEWORK='bootstrap-4'
    - php: 7.4
      env: LARAVEL='7.*' TESTBENCH='5.*' COMPOSER_FLAGS='--prefer-stable 'FORM_COMPONENTS_FRAMEWORK='bootstrap-4'
    - php: 7.4
      env: LARAVEL='8.*' TESTBENCH='6.*' COMPOSER_FLAGS='--prefer-lowest' FORM_COMPONENTS_FRAMEWORK='tailwind'
    - php: 7.4
      env: LARAVEL='8.*' TESTBENCH='6.*' COMPOSER_FLAGS='--prefer-stable 'FORM_COMPONENTS_FRAMEWORK='tailwind'
    - php: 7.4
      env: LARAVEL='8.*' TESTBENCH='6.*' COMPOSER_FLAGS='--prefer-lowest' FORM_COMPONENTS_FRAMEWORK='tailwind-2'
    - php: 7.4
      env: LARAVEL='8.*' TESTBENCH='6.*' COMPOSER_FLAGS='--prefer-stable 'FORM_COMPONENTS_FRAMEWORK='tailwind-2'
    - php: 7.4
      env: LARAVEL='8.*' TESTBENCH='6.*' COMPOSER_FLAGS='--prefer-lowest 'FORM_COMPONENTS_FRAMEWORK='bootstrap-4'
    - php: 7.4
      env: LARAVEL='8.*' TESTBENCH='6.*' COMPOSER_FLAGS='--prefer-stable 'FORM_COMPONENTS_FRAMEWORK='bootstrap-4'
  fast_finish: true

before_install:
  - composer config discard-changes true
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit